import { RegisteredComponent } from '@interfaces';

// export const dummyRegiUsers: Array<RegisteredComponent> = [
//   {
//     userId: 1,
//     menu: 'kor',
//     userImage: 'im1',
//     deadline: 5,
//     isAge: false,
//     age: 25,
//     comment: "Let's eat candies~",
//     sex: 'Male',
//     distance: 200,
//   },
//   {
//     userId: 2,
//     menu: 'jpn',
//     userImage: 'im2',
//     deadline: 10,
//     isAge: true,
//     age: 30,
//     comment: 'Sushi lover here!',
//     sex: 'Female',
//     distance: 150,
//   },
//   {
//     userId: 3,
//     menu: 'chn',
//     userImage: 'im3',
//     deadline: 15,
//     isAge: false,
//     age: 22,
//     comment: 'Dim sum, anyone?',
//     sex: 'Male',
//     distance: 300,
//   },
//   {
//     userId: 4,
//     menu: 'west',
//     userImage: 'im4',
//     deadline: 20,
//     isAge: true,
//     age: 28,
//     comment: 'Craving for pizza!',
//     sex: 'Female',
//     distance: 100,
//   },
//   {
//     userId: 5,
//     menu: 'others',
//     userImage: 'im5',
//     deadline: 5,
//     isAge: false,
//     age: 35,
//     comment: 'Exploring new cuisines!',
//     sex: 'Male',
//     distance: 250,
//   },
//   {
//     userId: 6,
//     menu: 'kor',
//     userImage: 'im6',
//     deadline: 10,
//     isAge: true,
//     age: 27,
//     comment: 'Kimchi forever!',
//     sex: 'Female',
//     distance: 180,
//   },
//   {
//     userId: 7,
//     menu: 'jpn',
//     userImage: 'im7',
//     deadline: 15,
//     isAge: false,
//     age: 24,
//     comment: 'Ramen time!',
//     sex: 'Male',
//     distance: 220,
//   },
//   {
//     userId: 8,
//     menu: 'chn',
//     userImage: 'im8',
//     deadline: 20,
//     isAge: true,
//     age: 31,
//     comment: 'Hot pot party!',
//     sex: 'Female',
//     distance: 130,
//   },
//   {
//     userId: 9,
//     menu: 'west',
//     userImage: 'im9',
//     deadline: 5,
//     isAge: false,
//     age: 29,
//     comment: 'Burger and fries, please!',
//     sex: 'Male',
//     distance: 280,
//   },
//   {
//     userId: 10,
//     menu: 'others',
//     userImage: 'im10',
//     deadline: 10,
//     isAge: true,
//     age: 26,
//     comment: 'Trying out exotic flavors!',
//     sex: 'Female',
//     distance: 190,
//   },
// ];
